# Generated by Django 2.2.7 on 2019-11-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactpage_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='handle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='platform_name',
            field=models.CharField(choices=[('github', 'Github'), ('stack-overflow', 'Stack Overflow'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=100),
        ),
    ]
