# Generated by Django 2.2.7 on 2019-11-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20191120_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='link',
            field=models.CharField(max_length=280),
        ),
    ]
