# Generated by Django 2.0.8 on 2018-08-11 19:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='info',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
