# Generated by Django 2.2.7 on 2019-11-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191111_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='', max_length=280),
            preserve_default=False,
        ),
    ]
