# Generated by Django 2.2.7 on 2019-11-23 17:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
