# Generated by Django 2.0.7 on 2018-07-17 02:50

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('workplace', models.CharField(max_length=50)),
                ('time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
